// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `is_supported_response_key`, `response_key_name`

/// Resolves Happ/V2RayTun/INCY wrappers and decrypts recognized encrypted links.
Future<String> resolveSubscriptionInput({required String input}) => RustLib
    .instance
    .api
    .crateApiSubscriptionResolveSubscriptionInput(input: input);

/// Removes Happ's optional AES-GCM response layer while leaving plain responses unchanged.
Future<Uint8List> decryptSubscriptionResponse({
  required String url,
  required List<int> body,
  String? encryptTag,
}) => RustLib.instance.api.crateApiSubscriptionDecryptSubscriptionResponse(
  url: url,
  body: body,
  encryptTag: encryptTag,
);
